"""Source-exact absolute-v31 normalization control.

The batch equations are the frozen numeric specification.  The streaming API
is the production path and retains only O(K + N) layer state.
"""

from .absolute_v31 import (
    FinalizedLayerNormalization,
    FinalizedMatrix,
    MatrixInput,
    decode_with_stored,
    fit_layer_absolute_normalization,
    regularize_from_stored,
    tensor_identity_sha256,
    tensor_sha256,
)
from .streaming_v31 import (
    BitSpecificGSS,
    FitSamplePlan,
    FitSampleSpec,
    StreamingAbsoluteNormalizationFit,
    StreamingLayerFitter,
    StreamingNormalizationManifest,
    StreamingPreparedMatrix,
    StreamingTopologyLedger,
)
from .artifact_v31 import (
    GSS_RECEIPT_SCHEMA,
    SCHEMA as ABSOLUTE_V31_ARTIFACT_SCHEMA,
    AbsoluteV31Artifact,
    AbsoluteV31BaselineArtifact,
    AdditiveV31CandidateResult,
    CandidateEvaluation,
    PinnedGSSProducer,
    PinnedGSSRequest,
    PinnedGSSResult,
    load_absolute_v31_artifact,
    evaluate_additive_v31_candidate,
    make_candidate_evaluation,
    make_gss_receipt,
    produce_absolute_v31_artifact,
    save_absolute_v31_artifact,
    verify_absolute_v31_artifact,
)
from .prior_search import (
    PERMUTATION_POLICIES,
    SCALE_FAMILIES,
    SCALE_GRID,
    coordinate_grid_scales,
    functional_oracle,
    policy_permutations,
    scale_family_candidates,
)

__all__ = [
    "BitSpecificGSS",
    "ABSOLUTE_V31_ARTIFACT_SCHEMA",
    "AbsoluteV31Artifact",
    "AbsoluteV31BaselineArtifact",
    "AdditiveV31CandidateResult",
    "CandidateEvaluation",
    "FinalizedLayerNormalization",
    "FinalizedMatrix",
    "FitSamplePlan",
    "FitSampleSpec",
    "MatrixInput",
    "StreamingAbsoluteNormalizationFit",
    "StreamingLayerFitter",
    "StreamingNormalizationManifest",
    "StreamingPreparedMatrix",
    "StreamingTopologyLedger",
    "GSS_RECEIPT_SCHEMA",
    "PinnedGSSProducer",
    "PinnedGSSRequest",
    "PinnedGSSResult",
    "PERMUTATION_POLICIES",
    "SCALE_FAMILIES",
    "SCALE_GRID",
    "coordinate_grid_scales",
    "decode_with_stored",
    "fit_layer_absolute_normalization",
    "functional_oracle",
    "evaluate_additive_v31_candidate",
    "load_absolute_v31_artifact",
    "make_gss_receipt",
    "make_candidate_evaluation",
    "policy_permutations",
    "produce_absolute_v31_artifact",
    "regularize_from_stored",
    "tensor_identity_sha256",
    "tensor_sha256",
    "save_absolute_v31_artifact",
    "scale_family_candidates",
    "verify_absolute_v31_artifact",
]
